services:
  apps:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: cinema-booking-app
    restart: unless-stopped
    ports:
      - "3125:3125"
      
networks:
    default: